<template>
  <el-container>
    <el-header>Header</el-header>
    <el-container>
      <el-container>
        <el-main>Main</el-main>
        <el-footer>Footer</el-footer>
      </el-container>
    </el-container>
  </el-container>
</template>
